### PR TITLE
merge troubleshootings to readme for better reference

### PR DESCRIPTION
**Pull request by tnga**
According to some dicussion, wink https://github.com/PedroHLC/osdlyrics/pull/23

### CODE REVIEW

**Comment by lenoch** [comment]
I use the following command to avoid creating merge commits when synchronizing work:

`git pull pedroHLC 0.5-series` (the parameters are: the remote name, the remote branch)

But I guess the remote has to be added first:
`git remote add pedroHLC git@github.com:pedroHLC/osdlyrics.git`

**Comment by lenoch** [comment]
Also, I separate work in branches so the main branch stays clear and can always be updated.

**Comment by PedroHLC** [comment]
If you guys would prefer to, I can put this repo on an github organization, you just have to choose it's name

**Comment by lenoch** [comment]
I have no preference in regard to setting up an organization. But if it were to be created, I'd like it to be named osdlyrics (OsdLyrics?), obviously, to indicate we'd like to push the project forward :-)

Actually... Before making a release, we should do something with branches (like I've done in my repo already) and that would be better done in a dedicated place -- your repo it is, but if you'd like to create something more official, I think it's alright to go ahead.

**Comment by tnga** [comment]
@lenoch normally when necessary, i also do the same. Effectively that one of things that i like with git usage. But when work to different machine (at home, at school, personal laptop),  sometime i lose feeling of current advanced development or reflex to pull before making any changes. I'am working to prevent that :smile: .

@PedroHLC I thing that we can wait for 0.6 version following the @lenoch preview's roadmap before create another organization. Therefore the new name we will choose for the project can also be  the organization's name. But it's just my point of view.

**Comment by PedroHLC** [comment]
Before doing it. What do you guys think?:
0.4 -> legacy-stable
master -> legacy-dev
develop -> legacy-dev2
0.5-series -> master

**Comment by lenoch** [comment]
Agreed, the names are precise.

**Comment by tnga** [comment]
:+1:

**Pull request merged**
