### PR TITLE
Add a roadmap

### PR DESCRIPTION
**Pull request by lenoch**
This is a reincarnation of ISSUES.md file, written from scratch. (troubleshooting.md should be merged into README, which itself should be updated slightly.)

I don't think everything I wrote must be set in stone but I hope points I make will become reasonable with some amendments by you.

### CODE REVIEW

**Comment by lenoch** [comment]
Old ISSUES.md, for reference: https://github.com/PedroHLC/osdlyrics/pull/13

**Comment by PedroHLC** [comment]
> MPRIS 1.0 works quite well but timing becomes inaccurate when a player seeks to anywhere but the beginning of a track.

That's something interesting, maybe comparing it with 0.4 C code might help.

> I couldn't get MPRIS 2.x to work well with VLC or Audacious.

Me neither

> What is this HTTP controller supposed to do?

Seems like a protocol for controling osdlyrics through HTTP requests that actually worked well with a player API, don't see why one would use it, HTTP uses TCP which has a giant latency, but TigerSolider must had found some reason.

**I do agree with all the rest**, as I finish some things in physical life I might be able to help with programming, that would be, post 4 Jan.

Closing and merging....

**Comment by tnga** [comment]
:+1:

**Comment by lenoch** [comment]
>> MPRIS 1.0 works quite well but timing becomes inaccurate when a player seeks to anywhere but the beginning of a track.

> That's something interesting, maybe comparing it with 0.4 C code might help.

Thanks. I think there are just a few places in the code where the internal timer is changed.

**Pull request merged**
