### PR TITLE
ISSUES.md: where I propose changes to the development/release model and describe two bugs

### PR DESCRIPTION
**Pull request by lenoch**
I think of your fork as the de-facto upstream now. Thank you for maintaining it! :-)

I just went ahead and started a file to track known bugs and sketch ideas for future development. I welcome everyone to comment and discuss.

### CODE REVIEW

**Comment by PedroHLC** [comment]
I wish Tigersoldier had left a roadmap of v0.5 there are lots of not yet programmed features, I would take a different approach, would rename the project to "osdlyrics-reloaded" rename "0.4" to "classic" and "0.5" to "master" and get rid of others branches, when all the holes were fixed, then would release it as 1.0 and create a new branch "stable" (thats just an idea, please discuss it).

**Comment by lenoch** [comment]
I am in favour of your proposed handling of branches, that is, calling 0.4 classic or legacy, and making 0.5 the master branch. I don't think the project needs renaming that much but I don't object at all :-)

I am fine with having a 1.0 release once bugs are triaged, unless we come up with some sort of a roadmap for intermediate 0.6 and 0.8 milestones with small feature additions or just some sort of goals achieved.

Can you name some of the missing features? I certainly think there are some things to wish for, but haven't made a list myself.

I started to clean up Python code in my clone with the goal of supporting Python 3. First, I want to get rid of incompatible language features and polish the code a bit so automatic checkers like pyflakes and PEP8 don't complain that much. Then, I would prefer to make the switch without maintaining compatibility with Python 2, which would save me from adding a dependency on python-six and making the code needlessly complicated due to support for both Python generations (there were some renames/moves in libraries).

While at it, I would like to restore MPRIS 1.0 support to match 0.4 functionality, that is, restore periodical polling which is unfortunately inherent to this older standard.

**Comment by tnga** [comment]
Good initiative, but about the rename of project, not think that is really necessary or just find a short name like *osdok*, *osdkaraok*, *boomlyrics*, *rhythmlyrics*, ...

**Comment by tnga** [comment]
I have already added a `troubleshooting.md` for discribing issues like those you ( @lenoch ) discribed to your `ISSUES.md`. It will be good if we have a only file for that. So you can use it or rename it to `ISSUES.md` ;).

**Comment by lenoch** [comment]
@tnga: ISSUES.md was supposed to be a list of problems to solve in the active development rather than guidance/troubleshooting notes for use when compiling the legacy one :-)

In my clone, I went ahead with the work I described: I removed stale branches, renamed "master" to "legacy" to make room for the new master, renamed from 0.5-series.

I also fixed (well, pretty much) OSD Lyrics' reaction to a player seeking (with MPRIS1).

**Comment by tnga** [comment]
ok, but *troubleshooting* was not just for guidance to use when make a compilation. Maybe i started to describe it like that but the final way was to mention issues on development in general and erase them when they will be solve (or just mention that they have been solved). I insist about that cause i think that it will be more efficient if we have less files to manage, especially if they are pretty similar (excluding the mains development sources in certains case) !!!

**Comment by lenoch** [comment]
I understand the term "troubleshooting" rather as something a user is advised to do in the case of a problem. The guidance you give there is mostly relevant to compiling the legacy master branch, and the issues are already solved in the 0.5-series branch.

Perhaps it would be useful to merge the notes into a Troubleshooting section in README.md to make them more visible to users.

I won't push my ISSUES.md in this legacy master branch. I used this pull request as a way to ask you about the direction the project should take, or rather inform you that I would we going there in my own clone. It's up to later discussion in my future pull requests to say if you like where I am going, or not.

**Comment by tnga** [comment]
For the work  you have done since your recents PR,  i really like and appreciate it. :+1: . However, sometime, it just necessary to discuss about some changes and therefore have clarification depending of our point of view :). i just stay tuned for now. ;)

**Comment by lenoch** [comment]
If you notice anything you don't like, please comment early :-)

**Pull request closed without merging**
