### PR TITLE
Master: make some fixes and update the readme file

### PR DESCRIPTION
**Pull request by tnga**

### CODE REVIEW

**Comment by PedroHLC** [comment]
I know it wasn't your intentions, but you're quietly undoing commit cb2c414ebef35fa53a930524c40595144c43618e

**Comment by tnga** [comment]
Yes the reason it because my fork is from **osdlyrics/osdlyrics** repo; when compiling the source i had some problems. I decided to fixed it and push it, but after that i saw there were on waiting pull requests which already fixed some of that problems and your fork is the most maintained. So i decided to review my repo, adjust changes that were already pushed to make it update with your own. Effectively it wasn't my intentions to make quietly commit.

**Comment by tnga** [comment]
i'm working to a new design and to a webapp port. But because of time it will take a while. I like the **viewLyric** add-ons to the project :+1:. It more efficient.

**Comment by tnga** [comment]
I think that @tigersoldier have to add other administrator like you @PedroHLC to make official repo more maintained. However *things are they are* and* we just do the most we can do*

**Pull request merged**
